apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    meta.helm.sh/release-name: media-wiki
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    nginx.ingress.kubernetes.io/rewrite-target: /mediawiki/$1
spec:
  ingressClassName: nginx-example
  tls:
  - hosts:
    - example.dns.com
  secretName: {{ .Values.SecretName }}
  rules:
  - http:
      paths:
      - path: {{ .Values.PathName }}
        pathType: Prefix
        backend:
          service:
            name: mediawiki
            port:
              number: {{ .Values.port }}
      - path: /mediawiki/(.*)
        pathType: Prefix
        backend:
          service:
            name: mediawiki
            port:
              number: {{ .Values.port }}
